// ============================================================
// StartupOS — Mock Data for Development
// ============================================================

import type {
  Customer,
  Deal,
  Project,
  Task,
  Activity,
  User,
  Pipeline,
  DashboardMetrics,
  Notification,
} from "@/types";

const ORG_ID = "org_1";
const USER_IDS = ["user_1", "user_2", "user_3", "user_4", "user_5"];

export const mockUsers: User[] = [
  {
    id: "user_1",
    organizationId: ORG_ID,
    firebaseUid: "firebase_1",
    email: "alex@startupos.io",
    displayName: "Alex Morgan",
    avatarUrl: `https://api.dicebear.com/7.x/avataaars/svg?seed=alex`,
    role: "owner",
    isActive: true,
    lastSeenAt: new Date().toISOString(),
    createdBy: "user_1",
    updatedBy: "user_1",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: new Date().toISOString(),
    notificationPreferences: {
      inApp: true,
      email: true,
      push: true,
      taskAssigned: true,
      dealUpdates: true,
      mentions: true,
      dueDates: true,
      comments: true,
    },
  },
  {
    id: "user_2",
    organizationId: ORG_ID,
    firebaseUid: "firebase_2",
    email: "sarah@startupos.io",
    displayName: "Sarah Chen",
    avatarUrl: `https://api.dicebear.com/7.x/avataaars/svg?seed=sarah`,
    role: "sales_manager",
    isActive: true,
    lastSeenAt: new Date().toISOString(),
    createdBy: "user_1",
    updatedBy: "user_1",
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: new Date().toISOString(),
    notificationPreferences: {
      inApp: true,
      email: true,
      push: false,
      taskAssigned: true,
      dealUpdates: true,
      mentions: true,
      dueDates: true,
      comments: false,
    },
  },
  {
    id: "user_3",
    organizationId: ORG_ID,
    firebaseUid: "firebase_3",
    email: "james@startupos.io",
    displayName: "James Park",
    avatarUrl: `https://api.dicebear.com/7.x/avataaars/svg?seed=james`,
    role: "project_manager",
    isActive: true,
    lastSeenAt: new Date().toISOString(),
    createdBy: "user_1",
    updatedBy: "user_1",
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: new Date().toISOString(),
    notificationPreferences: {
      inApp: true,
      email: false,
      push: false,
      taskAssigned: true,
      dealUpdates: false,
      mentions: true,
      dueDates: true,
      comments: true,
    },
  },
  {
    id: "user_4",
    organizationId: ORG_ID,
    firebaseUid: "firebase_4",
    email: "priya@startupos.io",
    displayName: "Priya Sharma",
    avatarUrl: `https://api.dicebear.com/7.x/avataaars/svg?seed=priya`,
    role: "team_member",
    isActive: true,
    lastSeenAt: new Date().toISOString(),
    createdBy: "user_1",
    updatedBy: "user_1",
    createdAt: "2024-02-15T00:00:00Z",
    updatedAt: new Date().toISOString(),
    notificationPreferences: {
      inApp: true,
      email: true,
      push: true,
      taskAssigned: true,
      dealUpdates: false,
      mentions: true,
      dueDates: true,
      comments: true,
    },
  },
  {
    id: "user_5",
    organizationId: ORG_ID,
    firebaseUid: "firebase_5",
    email: "mike@startupos.io",
    displayName: "Mike Torres",
    avatarUrl: `https://api.dicebear.com/7.x/avataaars/svg?seed=mike`,
    role: "team_member",
    isActive: true,
    lastSeenAt: new Date().toISOString(),
    createdBy: "user_1",
    updatedBy: "user_1",
    createdAt: "2024-03-01T00:00:00Z",
    updatedAt: new Date().toISOString(),
    notificationPreferences: {
      inApp: true,
      email: false,
      push: false,
      taskAssigned: true,
      dealUpdates: false,
      mentions: true,
      dueDates: false,
      comments: false,
    },
  },
];

export const mockCustomers: Customer[] = [
  {
    id: "cust_1",
    organizationId: ORG_ID,
    name: "Anthropic",
    website: "anthropic.com",
    industry: "technology",
    status: "customer",
    revenue: 4200000,
    employeeCount: 480,
    tags: ["ai", "enterprise", "strategic"],
    ownerId: "user_2",
    logoUrl: "https://logo.clearbit.com/anthropic.com",
    createdBy: "user_1",
    updatedBy: "user_2",
    createdAt: "2024-01-10T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
    address: { city: "San Francisco", state: "CA", country: "USA" },
  },
  {
    id: "cust_2",
    organizationId: ORG_ID,
    name: "Stripe",
    website: "stripe.com",
    industry: "finance",
    status: "customer",
    revenue: 8900000,
    employeeCount: 8000,
    tags: ["fintech", "payments", "enterprise"],
    ownerId: "user_2",
    logoUrl: "https://logo.clearbit.com/stripe.com",
    createdBy: "user_1",
    updatedBy: "user_1",
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: "2024-05-20T00:00:00Z",
    address: { city: "San Francisco", state: "CA", country: "USA" },
  },
  {
    id: "cust_3",
    organizationId: ORG_ID,
    name: "Figma",
    website: "figma.com",
    industry: "technology",
    status: "prospect",
    revenue: 2100000,
    employeeCount: 1200,
    tags: ["design", "saas", "mid-market"],
    ownerId: "user_2",
    logoUrl: "https://logo.clearbit.com/figma.com",
    createdBy: "user_2",
    updatedBy: "user_2",
    createdAt: "2024-03-15T00:00:00Z",
    updatedAt: "2024-06-10T00:00:00Z",
    address: { city: "San Francisco", state: "CA", country: "USA" },
  },
  {
    id: "cust_4",
    organizationId: ORG_ID,
    name: "Notion",
    website: "notion.so",
    industry: "technology",
    status: "lead",
    revenue: 960000,
    employeeCount: 400,
    tags: ["productivity", "saas"],
    ownerId: "user_1",
    logoUrl: "https://logo.clearbit.com/notion.so",
    createdBy: "user_1",
    updatedBy: "user_1",
    createdAt: "2024-04-01T00:00:00Z",
    updatedAt: "2024-06-05T00:00:00Z",
    address: { city: "San Francisco", state: "CA", country: "USA" },
  },
  {
    id: "cust_5",
    organizationId: ORG_ID,
    name: "Linear",
    website: "linear.app",
    industry: "technology",
    status: "prospect",
    revenue: 450000,
    employeeCount: 120,
    tags: ["productivity", "startup"],
    ownerId: "user_2",
    logoUrl: "https://logo.clearbit.com/linear.app",
    createdBy: "user_2",
    updatedBy: "user_2",
    createdAt: "2024-04-20T00:00:00Z",
    updatedAt: "2024-06-12T00:00:00Z",
    address: { city: "San Francisco", state: "CA", country: "USA" },
  },
  {
    id: "cust_6",
    organizationId: ORG_ID,
    name: "Vercel",
    website: "vercel.com",
    industry: "technology",
    status: "customer",
    revenue: 3200000,
    employeeCount: 550,
    tags: ["cloud", "developer-tools", "enterprise"],
    ownerId: "user_1",
    logoUrl: "https://logo.clearbit.com/vercel.com",
    createdBy: "user_1",
    updatedBy: "user_1",
    createdAt: "2024-02-10T00:00:00Z",
    updatedAt: "2024-05-30T00:00:00Z",
    address: { city: "San Francisco", state: "CA", country: "USA" },
  },
  {
    id: "cust_7",
    organizationId: ORG_ID,
    name: "GitHub",
    website: "github.com",
    industry: "technology",
    status: "customer",
    revenue: 12000000,
    employeeCount: 3500,
    tags: ["developer-tools", "enterprise", "strategic"],
    ownerId: "user_2",
    logoUrl: "https://logo.clearbit.com/github.com",
    createdBy: "user_1",
    updatedBy: "user_2",
    createdAt: "2024-01-05T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
    address: { city: "San Francisco", state: "CA", country: "USA" },
  },
  {
    id: "cust_8",
    organizationId: ORG_ID,
    name: "Airbnb",
    website: "airbnb.com",
    industry: "technology",
    status: "lead",
    revenue: 0,
    employeeCount: 6000,
    tags: ["marketplace", "enterprise", "travel"],
    ownerId: "user_1",
    logoUrl: "https://logo.clearbit.com/airbnb.com",
    createdBy: "user_1",
    updatedBy: "user_1",
    createdAt: "2024-05-01T00:00:00Z",
    updatedAt: "2024-06-10T00:00:00Z",
    address: { city: "San Francisco", state: "CA", country: "USA" },
  },
];

export const mockPipeline: Pipeline = {
  id: "pipeline_1",
  organizationId: ORG_ID,
  name: "Sales Pipeline",
  isDefault: true,
  currency: "USD",
  createdBy: "user_1",
  updatedBy: "user_1",
  createdAt: "2024-01-01T00:00:00Z",
  updatedAt: "2024-01-01T00:00:00Z",
  stages: [
    { id: "stage_lead", name: "Lead", order: 0, color: "#6366f1", probability: 10, isWon: false, isLost: false },
    { id: "stage_qualified", name: "Qualified", order: 1, color: "#8b5cf6", probability: 25, isWon: false, isLost: false },
    { id: "stage_demo", name: "Demo", order: 2, color: "#a855f7", probability: 40, isWon: false, isLost: false },
    { id: "stage_proposal", name: "Proposal", order: 3, color: "#d946ef", probability: 60, isWon: false, isLost: false },
    { id: "stage_negotiation", name: "Negotiation", order: 4, color: "#ec4899", probability: 80, isWon: false, isLost: false },
    { id: "stage_won", name: "Won", order: 5, color: "#22c55e", probability: 100, isWon: true, isLost: false },
    { id: "stage_onboarding", name: "Onboarding", order: 6, color: "#3b82f6", probability: 100, isWon: true, isLost: false },
  ],
};

export const mockDeals: Deal[] = [
  {
    id: "deal_1",
    organizationId: ORG_ID,
    title: "Anthropic — Enterprise Suite",
    customerId: "cust_1",
    pipelineId: "pipeline_1",
    stageId: "stage_negotiation",
    value: 480000,
    currency: "USD",
    probability: 80,
    priority: "critical",
    ownerId: "user_2",
    expectedCloseDate: "2024-07-30T00:00:00Z",
    tags: ["enterprise", "annual"],
    isWon: false,
    isLost: false,
    score: 87,
    createdBy: "user_2",
    updatedBy: "user_2",
    createdAt: "2024-04-10T00:00:00Z",
    updatedAt: "2024-06-10T00:00:00Z",
  },
  {
    id: "deal_2",
    organizationId: ORG_ID,
    title: "Stripe — Platform Integration",
    customerId: "cust_2",
    pipelineId: "pipeline_1",
    stageId: "stage_proposal",
    value: 320000,
    currency: "USD",
    probability: 60,
    priority: "high",
    ownerId: "user_2",
    expectedCloseDate: "2024-08-15T00:00:00Z",
    tags: ["integration", "annual"],
    isWon: false,
    isLost: false,
    score: 74,
    createdBy: "user_2",
    updatedBy: "user_2",
    createdAt: "2024-03-20T00:00:00Z",
    updatedAt: "2024-06-08T00:00:00Z",
  },
  {
    id: "deal_3",
    organizationId: ORG_ID,
    title: "Figma — Design Team License",
    customerId: "cust_3",
    pipelineId: "pipeline_1",
    stageId: "stage_demo",
    value: 96000,
    currency: "USD",
    probability: 40,
    priority: "medium",
    ownerId: "user_1",
    expectedCloseDate: "2024-09-01T00:00:00Z",
    tags: ["saas", "monthly"],
    isWon: false,
    isLost: false,
    score: 52,
    createdBy: "user_1",
    updatedBy: "user_1",
    createdAt: "2024-05-05T00:00:00Z",
    updatedAt: "2024-06-05T00:00:00Z",
  },
  {
    id: "deal_4",
    organizationId: ORG_ID,
    title: "Notion — Workspace Rollout",
    customerId: "cust_4",
    pipelineId: "pipeline_1",
    stageId: "stage_qualified",
    value: 48000,
    currency: "USD",
    probability: 25,
    priority: "low",
    ownerId: "user_1",
    expectedCloseDate: "2024-10-01T00:00:00Z",
    tags: ["smb"],
    isWon: false,
    isLost: false,
    score: 34,
    createdBy: "user_1",
    updatedBy: "user_1",
    createdAt: "2024-05-20T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "deal_5",
    organizationId: ORG_ID,
    title: "Vercel — Annual Renewal",
    customerId: "cust_6",
    pipelineId: "pipeline_1",
    stageId: "stage_won",
    value: 240000,
    currency: "USD",
    probability: 100,
    priority: "high",
    ownerId: "user_2",
    expectedCloseDate: "2024-06-01T00:00:00Z",
    actualCloseDate: "2024-06-01T00:00:00Z",
    tags: ["renewal", "annual"],
    isWon: true,
    isLost: false,
    score: 100,
    projectId: "proj_1",
    createdBy: "user_2",
    updatedBy: "user_2",
    createdAt: "2024-04-01T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "deal_6",
    organizationId: ORG_ID,
    title: "GitHub — Developer Tools Bundle",
    customerId: "cust_7",
    pipelineId: "pipeline_1",
    stageId: "stage_onboarding",
    value: 720000,
    currency: "USD",
    probability: 100,
    priority: "critical",
    ownerId: "user_2",
    expectedCloseDate: "2024-05-15T00:00:00Z",
    actualCloseDate: "2024-05-15T00:00:00Z",
    tags: ["enterprise", "annual", "strategic"],
    isWon: true,
    isLost: false,
    score: 100,
    projectId: "proj_2",
    createdBy: "user_2",
    updatedBy: "user_2",
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: "2024-05-15T00:00:00Z",
  },
  {
    id: "deal_7",
    organizationId: ORG_ID,
    title: "Linear — Startup Plan",
    customerId: "cust_5",
    pipelineId: "pipeline_1",
    stageId: "stage_lead",
    value: 24000,
    currency: "USD",
    probability: 10,
    priority: "low",
    ownerId: "user_1",
    expectedCloseDate: "2024-11-01T00:00:00Z",
    tags: ["startup"],
    isWon: false,
    isLost: false,
    score: 18,
    createdBy: "user_1",
    updatedBy: "user_1",
    createdAt: "2024-06-01T00:00:00Z",
    updatedAt: "2024-06-12T00:00:00Z",
  },
  {
    id: "deal_8",
    organizationId: ORG_ID,
    title: "Airbnb — Marketplace Analytics",
    customerId: "cust_8",
    pipelineId: "pipeline_1",
    stageId: "stage_lead",
    value: 180000,
    currency: "USD",
    probability: 10,
    priority: "medium",
    ownerId: "user_1",
    expectedCloseDate: "2024-12-01T00:00:00Z",
    tags: ["enterprise", "new"],
    isWon: false,
    isLost: false,
    score: 22,
    createdBy: "user_1",
    updatedBy: "user_1",
    createdAt: "2024-06-10T00:00:00Z",
    updatedAt: "2024-06-12T00:00:00Z",
  },
];

export const mockProjects: Project[] = [
  {
    id: "proj_1",
    organizationId: ORG_ID,
    name: "Vercel Platform Migration",
    description: "Full migration of Vercel's internal tooling to our platform.",
    customerId: "cust_6",
    dealId: "deal_5",
    status: "active",
    priority: "high",
    ownerId: "user_3",
    teamIds: ["user_3", "user_4", "user_5"],
    startDate: "2024-06-03T00:00:00Z",
    endDate: "2024-09-30T00:00:00Z",
    progress: 32,
    tags: ["migration", "enterprise"],
    milestones: [
      { id: "ms_1", name: "Discovery & Architecture", dueDate: "2024-06-30T00:00:00Z", isCompleted: true, completedAt: "2024-06-28T00:00:00Z", taskIds: [] },
      { id: "ms_2", name: "Core Integration", dueDate: "2024-07-31T00:00:00Z", isCompleted: false, taskIds: [] },
      { id: "ms_3", name: "Testing & QA", dueDate: "2024-08-31T00:00:00Z", isCompleted: false, taskIds: [] },
      { id: "ms_4", name: "Go-Live", dueDate: "2024-09-30T00:00:00Z", isCompleted: false, taskIds: [] },
    ],
    sprints: [
      { id: "sp_1", name: "Sprint 1 — Setup", startDate: "2024-06-03T00:00:00Z", endDate: "2024-06-16T00:00:00Z", status: "completed", taskIds: [] },
      { id: "sp_2", name: "Sprint 2 — Core APIs", startDate: "2024-06-17T00:00:00Z", endDate: "2024-06-30T00:00:00Z", status: "active", taskIds: [] },
    ],
    createdBy: "user_1",
    updatedBy: "user_3",
    createdAt: "2024-06-01T00:00:00Z",
    updatedAt: "2024-06-12T00:00:00Z",
  },
  {
    id: "proj_2",
    organizationId: ORG_ID,
    name: "GitHub Developer Tools",
    description: "Implementing developer tooling suite for GitHub's engineering team.",
    customerId: "cust_7",
    dealId: "deal_6",
    status: "active",
    priority: "critical",
    ownerId: "user_3",
    teamIds: ["user_3", "user_4"],
    startDate: "2024-05-20T00:00:00Z",
    endDate: "2024-10-31T00:00:00Z",
    progress: 24,
    tags: ["developer-tools", "enterprise"],
    milestones: [
      { id: "ms_5", name: "Requirements Gathering", dueDate: "2024-06-01T00:00:00Z", isCompleted: true, completedAt: "2024-05-30T00:00:00Z", taskIds: [] },
      { id: "ms_6", name: "MVP Release", dueDate: "2024-08-01T00:00:00Z", isCompleted: false, taskIds: [] },
    ],
    sprints: [],
    createdBy: "user_1",
    updatedBy: "user_3",
    createdAt: "2024-05-16T00:00:00Z",
    updatedAt: "2024-06-10T00:00:00Z",
  },
  {
    id: "proj_3",
    organizationId: ORG_ID,
    name: "Anthropic Onboarding",
    description: "Customer onboarding and setup for Anthropic enterprise license.",
    customerId: "cust_1",
    status: "planning",
    priority: "high",
    ownerId: "user_3",
    teamIds: ["user_3", "user_5"],
    startDate: "2024-08-01T00:00:00Z",
    endDate: "2024-09-30T00:00:00Z",
    progress: 0,
    tags: ["onboarding", "enterprise"],
    milestones: [],
    sprints: [],
    createdBy: "user_3",
    updatedBy: "user_3",
    createdAt: "2024-06-10T00:00:00Z",
    updatedAt: "2024-06-10T00:00:00Z",
  },
  {
    id: "proj_4",
    organizationId: ORG_ID,
    name: "Internal Dashboard Redesign",
    description: "Redesigning internal analytics dashboard for better UX.",
    status: "review",
    priority: "medium",
    ownerId: "user_4",
    teamIds: ["user_4", "user_5"],
    startDate: "2024-04-01T00:00:00Z",
    endDate: "2024-06-30T00:00:00Z",
    progress: 85,
    tags: ["internal", "design"],
    milestones: [],
    sprints: [],
    createdBy: "user_3",
    updatedBy: "user_4",
    createdAt: "2024-03-28T00:00:00Z",
    updatedAt: "2024-06-08T00:00:00Z",
  },
];

export const mockTasks: Task[] = [
  {
    id: "task_1",
    organizationId: ORG_ID,
    title: "Set up authentication flow",
    type: "project",
    status: "in_progress",
    priority: "high",
    assigneeId: "user_4",
    projectId: "proj_1",
    dueDate: "2024-06-20T00:00:00Z",
    tags: ["backend", "auth"],
    estimatedHours: 8,
    subtasks: [],
    checklist: [
      { id: "cl_1", label: "Firebase Auth integration", isChecked: true },
      { id: "cl_2", label: "JWT token handling", isChecked: true },
      { id: "cl_3", label: "Refresh token logic", isChecked: false },
    ],
    dependencies: [],
    attachments: [],
    isRecurring: false,
    order: 0,
    createdBy: "user_3",
    updatedBy: "user_4",
    createdAt: "2024-06-10T00:00:00Z",
    updatedAt: "2024-06-14T00:00:00Z",
  },
  {
    id: "task_2",
    organizationId: ORG_ID,
    title: "Design system component library",
    type: "project",
    status: "done",
    priority: "high",
    assigneeId: "user_5",
    projectId: "proj_1",
    dueDate: "2024-06-15T00:00:00Z",
    tags: ["design", "frontend"],
    estimatedHours: 16,
    subtasks: [],
    checklist: [],
    dependencies: [],
    attachments: [],
    isRecurring: false,
    order: 1,
    createdBy: "user_3",
    updatedBy: "user_5",
    createdAt: "2024-06-05T00:00:00Z",
    updatedAt: "2024-06-15T00:00:00Z",
  },
  {
    id: "task_3",
    organizationId: ORG_ID,
    title: "Prepare enterprise proposal for Anthropic",
    type: "sales",
    status: "in_progress",
    priority: "urgent",
    assigneeId: "user_2",
    dealId: "deal_1",
    customerId: "cust_1",
    dueDate: "2024-06-18T00:00:00Z",
    tags: ["proposal", "enterprise"],
    estimatedHours: 4,
    subtasks: [],
    checklist: [
      { id: "cl_4", label: "Pricing breakdown", isChecked: true },
      { id: "cl_5", label: "Technical scope", isChecked: false },
      { id: "cl_6", label: "Executive summary", isChecked: false },
    ],
    dependencies: [],
    attachments: [],
    isRecurring: false,
    order: 0,
    createdBy: "user_2",
    updatedBy: "user_2",
    createdAt: "2024-06-12T00:00:00Z",
    updatedAt: "2024-06-14T00:00:00Z",
  },
  {
    id: "task_4",
    organizationId: ORG_ID,
    title: "API documentation",
    type: "project",
    status: "todo",
    priority: "medium",
    assigneeId: "user_4",
    projectId: "proj_2",
    dueDate: "2024-07-01T00:00:00Z",
    tags: ["docs", "api"],
    estimatedHours: 12,
    subtasks: [],
    checklist: [],
    dependencies: [{ taskId: "task_1", type: "blocked_by" }],
    attachments: [],
    isRecurring: false,
    order: 0,
    createdBy: "user_3",
    updatedBy: "user_3",
    createdAt: "2024-06-08T00:00:00Z",
    updatedAt: "2024-06-08T00:00:00Z",
  },
  {
    id: "task_5",
    organizationId: ORG_ID,
    title: "Weekly team standup",
    type: "project",
    status: "todo",
    priority: "low",
    assigneeId: "user_3",
    dueDate: "2024-06-17T00:00:00Z",
    tags: ["meeting"],
    estimatedHours: 1,
    subtasks: [],
    checklist: [],
    dependencies: [],
    attachments: [],
    isRecurring: true,
    recurringConfig: { frequency: "weekly", interval: 1 },
    order: 2,
    createdBy: "user_3",
    updatedBy: "user_3",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-06-10T00:00:00Z",
  },
  {
    id: "task_6",
    organizationId: ORG_ID,
    title: "Follow up with Stripe stakeholders",
    type: "sales",
    status: "todo",
    priority: "high",
    assigneeId: "user_2",
    dealId: "deal_2",
    customerId: "cust_2",
    dueDate: "2024-06-16T00:00:00Z",
    tags: ["followup", "outreach"],
    estimatedHours: 1,
    subtasks: [],
    checklist: [],
    dependencies: [],
    attachments: [],
    isRecurring: false,
    order: 1,
    createdBy: "user_2",
    updatedBy: "user_2",
    createdAt: "2024-06-11T00:00:00Z",
    updatedAt: "2024-06-11T00:00:00Z",
  },
  {
    id: "task_7",
    organizationId: ORG_ID,
    title: "Database schema optimization",
    type: "project",
    status: "backlog",
    priority: "medium",
    assigneeId: "user_5",
    projectId: "proj_2",
    tags: ["backend", "database"],
    estimatedHours: 6,
    subtasks: [],
    checklist: [],
    dependencies: [],
    attachments: [],
    isRecurring: false,
    order: 1,
    createdBy: "user_3",
    updatedBy: "user_3",
    createdAt: "2024-06-09T00:00:00Z",
    updatedAt: "2024-06-09T00:00:00Z",
  },
  {
    id: "task_8",
    organizationId: ORG_ID,
    title: "User acceptance testing",
    type: "project",
    status: "backlog",
    priority: "high",
    assigneeId: "user_4",
    projectId: "proj_4",
    dueDate: "2024-06-25T00:00:00Z",
    tags: ["qa", "testing"],
    estimatedHours: 10,
    subtasks: [],
    checklist: [],
    dependencies: [],
    attachments: [],
    isRecurring: false,
    order: 2,
    createdBy: "user_3",
    updatedBy: "user_3",
    createdAt: "2024-06-01T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
];

export const mockActivities: Activity[] = [
  {
    id: "act_1", organizationId: ORG_ID, type: "deal_won", entityType: "deal", entityId: "deal_5",
    entityName: "Vercel — Annual Renewal", userId: "user_2", comment: "Deal closed at $240K. Project created automatically.",
    createdBy: "user_2", updatedBy: "user_2", createdAt: "2024-06-01T10:30:00Z", updatedAt: "2024-06-01T10:30:00Z",
  },
  {
    id: "act_2", organizationId: ORG_ID, type: "project_created", entityType: "project", entityId: "proj_1",
    entityName: "Vercel Platform Migration", userId: "user_1", comment: "Project auto-created from won deal.",
    createdBy: "user_1", updatedBy: "user_1", createdAt: "2024-06-01T10:31:00Z", updatedAt: "2024-06-01T10:31:00Z",
  },
  {
    id: "act_3", organizationId: ORG_ID, type: "status_changed", entityType: "task", entityId: "task_2",
    entityName: "Design system component library", userId: "user_5",
    metadata: { from: "in_progress", to: "done" },
    createdBy: "user_5", updatedBy: "user_5", createdAt: "2024-06-15T09:00:00Z", updatedAt: "2024-06-15T09:00:00Z",
  },
  {
    id: "act_4", organizationId: ORG_ID, type: "commented", entityType: "deal", entityId: "deal_1",
    entityName: "Anthropic — Enterprise Suite", userId: "user_2", comment: "Had a great call. They are very interested in the enterprise tier.",
    createdBy: "user_2", updatedBy: "user_2", createdAt: "2024-06-14T15:20:00Z", updatedAt: "2024-06-14T15:20:00Z",
  },
  {
    id: "act_5", organizationId: ORG_ID, type: "assigned", entityType: "task", entityId: "task_1",
    entityName: "Set up authentication flow", userId: "user_3",
    metadata: { assigneeId: "user_4", assigneeName: "Priya Sharma" },
    createdBy: "user_3", updatedBy: "user_3", createdAt: "2024-06-10T11:00:00Z", updatedAt: "2024-06-10T11:00:00Z",
  },
  {
    id: "act_6", organizationId: ORG_ID, type: "created", entityType: "customer", entityId: "cust_8",
    entityName: "Airbnb", userId: "user_1", comment: "Added Airbnb as a new lead from conference.",
    createdBy: "user_1", updatedBy: "user_1", createdAt: "2024-06-10T08:30:00Z", updatedAt: "2024-06-10T08:30:00Z",
  },
  {
    id: "act_7", organizationId: ORG_ID, type: "status_changed", entityType: "project", entityId: "proj_4",
    entityName: "Internal Dashboard Redesign", userId: "user_4",
    metadata: { from: "active", to: "review" },
    createdBy: "user_4", updatedBy: "user_4", createdAt: "2024-06-08T14:00:00Z", updatedAt: "2024-06-08T14:00:00Z",
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "notif_1", organizationId: ORG_ID, userId: "user_1", type: "deal_won",
    title: "Deal Won! 🎉", body: "Vercel — Annual Renewal closed at $240,000",
    entityType: "deal", entityId: "deal_5", isRead: false,
    createdBy: "user_1", updatedBy: "user_1", createdAt: "2024-06-01T10:30:00Z", updatedAt: "2024-06-01T10:30:00Z",
  },
  {
    id: "notif_2", organizationId: ORG_ID, userId: "user_1", type: "task_assigned",
    title: "Task assigned to you", body: "James Park assigned \"User acceptance testing\" to you",
    entityType: "task", entityId: "task_8", isRead: false,
    createdBy: "user_3", updatedBy: "user_3", createdAt: "2024-06-14T11:00:00Z", updatedAt: "2024-06-14T11:00:00Z",
  },
  {
    id: "notif_3", organizationId: ORG_ID, userId: "user_1", type: "mention",
    title: "You were mentioned", body: "Sarah Chen mentioned you in Anthropic — Enterprise Suite",
    entityType: "deal", entityId: "deal_1", isRead: true, readAt: "2024-06-14T16:00:00Z",
    createdBy: "user_2", updatedBy: "user_2", createdAt: "2024-06-14T15:20:00Z", updatedAt: "2024-06-14T16:00:00Z",
  },
  {
    id: "notif_4", organizationId: ORG_ID, userId: "user_1", type: "due_date",
    title: "Task due today", body: "\"Follow up with Stripe stakeholders\" is due today",
    entityType: "task", entityId: "task_6", isRead: false,
    createdBy: "user_1", updatedBy: "user_1", createdAt: "2024-06-16T07:00:00Z", updatedAt: "2024-06-16T07:00:00Z",
  },
];

export const mockDashboardMetrics: DashboardMetrics = {
  leadsThisWeek: 12,
  leadsChange: 20,
  pipelineValue: 1848000,
  pipelineChange: 8.4,
  revenueForecasted: 960000,
  revenueChange: 14.2,
  activeProjects: 4,
  overdueTasks: 2,
  teamWorkload: [
    { userId: "user_2", userName: "Sarah Chen", assignedTasks: 12, completedTasks: 8, overdueTasks: 1 },
    { userId: "user_3", userName: "James Park", assignedTasks: 8, completedTasks: 5, overdueTasks: 0 },
    { userId: "user_4", userName: "Priya Sharma", assignedTasks: 15, completedTasks: 11, overdueTasks: 1 },
    { userId: "user_5", userName: "Mike Torres", assignedTasks: 6, completedTasks: 4, overdueTasks: 0 },
  ],
  recentActivities: mockActivities.slice(0, 5),
  revenueByMonth: [
    { month: "Jan", forecast: 180000, actual: 160000 },
    { month: "Feb", forecast: 220000, actual: 240000 },
    { month: "Mar", forecast: 280000, actual: 310000 },
    { month: "Apr", forecast: 320000, actual: 290000 },
    { month: "May", forecast: 380000, actual: 420000 },
    { month: "Jun", forecast: 450000, actual: 0 },
    { month: "Jul", forecast: 510000, actual: 0 },
    { month: "Aug", forecast: 580000, actual: 0 },
  ],
};

// Lookup helpers
export const getUserById = (id: string) => mockUsers.find((u) => u.id === id);
export const getCustomerById = (id: string) => mockCustomers.find((c) => c.id === id);
export const getDealById = (id: string) => mockDeals.find((d) => d.id === id);
export const getProjectById = (id: string) => mockProjects.find((p) => p.id === id);
